# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Dibs' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dibs
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'

  target 'DibsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DibsUITests' do
    # Pods for testing
  end

end
